"""new addition image

Revision ID: f8ad5f6816e2
Revises: bf14567abd5c
Create Date: 2023-10-25 10:29:32.979903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ad5f6816e2'
down_revision = 'bf14567abd5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=2000), nullable=False))
        batch_op.add_column(sa.Column('desciption', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_column('desciption')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
